- name: Play1
  hosts: localhost
  become: yes
  tasks:
    - name: Installing the lighttpd
      package:
        name: lighttpd
        state: present

    - name: Starting the service
      service:
        name: lighttpd
        state: started
        enabled: true

    - name: Creating a file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Adding a line to file
      copy:
        dest: /var/www/html/index.html
        content: |
          This is a sample website testing scenario.

    - name: Adding more content at the top
      lineinfile:
        path: /var/www/html/index.html
        insertbefore: BOF
        line: "<h1>Welcome to Testing Group!</h1>"
        state: present
        mode: "0644"

    - name: Starting the service
      service:
        name: lighttpd
        state: restarted
